### ISSUE TITLE
Prepare for promotion to core component

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/samvera-circleci-orb#19]
### Code Requirements
- [x] Code must be released at version >= 1.0
- [x] Good unit test coverage measured by community (e.g. 100% or 75% of what’s important)
  - Is this relevant?
- [x] uses CI (Preferably CircleCI, unless there is a compelling reason to do something else)
  - Is this relevant?
- [x] uses Coverage tool (coveralls or simplecov)
  - Is this relevant?
- [x] Show compatibility with current Rails versions and other dependencies, when was it last tested; note compatibility with prior versions when available. Compatibility can be specified in the gemspec(s) or verified via CI matrix.
- [x] Hierarchy of promises asserted in clearly defined acceptance tests

### Documentation Requirements
- [x] LICENSE file, Apache 2 (or compatible)
- [x] README.md
- [x] Statement of purpose
- [x] Basic install steps
- [x] Identify any volatile/experimental features
- [x] How to contribute -> CONTRIBUTING.md
- [x] How/Who to contact for help -> push out to all gems like CONTRIBUTING.md
- [x] Known issues documented in github Issues tickets (not just listed in text)
- [x] Tutorial / Walkthrough / Example usage
- [x] Resolve TODO items in documents and remove them
- [x] All Contributors should have signed Hydra Contibutor License Agreement (CLA)

### Use Requirements
- [x] Community use by three or more institutions
  - All core components use the orb now.
- [x] In active use for six months
  - ActiveFedora started using it on March 20th.
- [x] Has an ongoing maintenance plan.

**Comment by jrgriffiniii** [comment]
Given the current state of the documentation and support for integration tests (thank you very much for all of the labor on https://github.com/samvera-labs/samvera-circleci-orb/blob/main/.circleci/config.yml @rotated8 and @tpendragon), this seems to fulfill nearly every requirement. All that remains, which I can best determine, is that there be specified a product owner.

**Comment by jrgriffiniii** [comment]
The GitHub repository has been migrated to the `samvera` Organization, and the URL for the source code base has been updated with a new patch release on the CircleCI Orb registry: https://circleci.com/developer/orbs/orb/samvera/circleci-orb?version=1.0.2

**Comment by jrgriffiniii** [comment]
As this should now comply with the requirements for promotion for Samvera Core Components, I shall close this, and publish an announcement to the community as to the status of this new component. Thank you very much again @cjcolvar, @rotated8, and @bess!
