### ISSUE TITLE
As part of build, generate and store list of gem versions used

### ISSUE THREAD

**Issue by jeremyf** [samvera-labs/samvera-circleci-orb#28]
This week, I spent quite a bit of time tracking down what dependencies were used with build. I ended up writing a script that uses `bundle list` and determines the date of each gem version's release. (see https://github.com/samvera/maintenance/blob/master/script/bundled-gem-release-dates.rb)

The problem is exacerbated with our EngineCart practice, when we push up sometimes we bundle update other times we use the cache. Knowing what's in play for a given build takes considerable sleuthing.

What I am looking for is a simple way to look at a build and see the list of bundled gems used. We can kind of do this by looking at the bundle install, but with caching that may not be in each build. Ideally, we'd have a file that could say "these were the gem versions used for this build."

On my machine, `bundle list` takes 0.31s for Hyrax. I do not believe the generation of this artifact would add much more than 1s to a Hyrax build.

**Comment by rotated8** [comment]
This is now available on orb version "dev:a34fec0". A production version should be released soon.
