### ISSUE TITLE
Change default solr image

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/samvera-circleci-orb#33]
I ran into a weird CI build issue where one of the 10 parallelized containers failed with `error starting container solr:7-alpine: Error: No such image: solr:7-alpine`.  I went looking on dockerhub and sure enough it looks like there isn't a `7-alpine` anymore only `7` and `7-slim`.  I wonder if circleci is pulling from cache which will go away at some point and kill all of our builds.  It would be nice to change the default in the orb before 1.0.

Here is the failed build: https://app.circleci.com/pipelines/github/samvera/hyrax/3587/workflows/52f26ad0-121b-4fa2-bfe0-3f090856d2b3/jobs/23332

**Comment by rotated8** [comment]
I noticed this when I added the solr_version param. `7-alpine` still exists as a [tag in dockerhub](https://hub.docker.com/_/solr?tab=tags&page=1&name=7-alpine), but it hasn't been updated in almost a year. Meanwhile, `7-slim` was updated about two weeks ago.

**Comment by rotated8** [comment]
Closed as fixed in #34
