### ISSUE TITLE
Bundle command does not produce a reusable cache key

### ISSUE THREAD

**Issue by rotated8** [samvera-labs/samvera-circleci-orb#40]
Thanks to @cjcolvar for bringing this up.

In the parallel builds in a CI run (e.g. https://app.circleci.com/pipelines/github/samvera/hyrax/3718/workflows/e032bfbc-1c26-4add-83e4-1975bd88a336/jobs/24758), looking at the "Save bundle cache" step, the cache key is different for each run.

Leading suspect is the [`find` generating the cache key in the bundle command](https://github.com/samvera-labs/samvera-circleci-orb/blob/master/src/commands/bundle.yml#L17)

**Comment by cjcolvar** [comment]
:+1: Fixing this will save us time and $$ since fetching the entire bundle takes a lot of time (on the order of minutes for large repos).

**Comment by rotated8** [comment]
The issue appears to be that in different runs, `find` may produce its output in a different order, as seen in the screenshots below. 
![find1](https://user-images.githubusercontent.com/638392/87084806-d18fc100-c1fc-11ea-8489-4d1288a5b6fa.png)
![find2](https://user-images.githubusercontent.com/638392/87084819-d785a200-c1fc-11ea-8856-a829dc1a3249.png)
