### ISSUE TITLE
Add caching to rubocop?

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/samvera-circleci-orb#44]
I wonder if it makes sense to cache the output of rubocop to reduce the time it takes to run since our files aren't usually changing that much and it can save significant amount of time locally.  I'm not sure exactly how rubocop's caching works and if it would work to do it in a CI environment or what exactly the cache key should look like.

See https://docs.rubocop.org/rubocop/usage/caching.html

**Comment by rotated8** [comment]
Closing as fixed in #46
